<a href="https://colab.research.google.com/github/DomMcOyle/TACO-expl/blob/add_detr/Training%20notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

t = torch.randn(3,300,4)
batchindexes = torch.arange(3).reshape(3,1,1).repeat(1,300,1)
print(batchindexes.shape)
#print(batchindexes)
idx = torch.cat([batchindexes, t], -1)
print(idx.shape)
print(idx[0, 299, :])
idx = idx.reshape(3*300, 5)
print(idx.shape)
print(idx[299,:])

#print(t[-1, :, :].shape)
#print(t.repeat(1,1,4))
#t.view(t.shape[0], -1).shape

torch.Size([3, 300, 1])
torch.Size([3, 300, 5])
tensor([ 0.0000, -3.3577, -0.2601,  0.2991, -1.2073])
torch.Size([900, 5])
tensor([ 0.0000, -3.3577, -0.2601,  0.2991, -1.2073])


In [1]:
!git clone https://github.com/DomMcOyle/TACO-expl
%cd /content/TACO-expl/
!git checkout add_detr
%cd /content/

fatal: destination path 'TACO-expl' already exists and is not an empty directory.
/content/TACO-expl
M	HDDETR/models/deformable_transformer.py
Already on 'add_detr'
Your branch is up to date with 'origin/add_detr'.
/content


In [ ]:
%cd /content/TACO-expl/HDDETR
!pip install -r requirements.txt
!pip install mmcv==2.1.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.1/index.html
!pip install mmdet
%cd /content/TACO-expl/HDDETR/models/ops
!python setup.py build install
# unit test (should see all checking is True)
#!python test.py
%cd /content/

In [1]:
import os.path
import json
import argparse
import numpy as np
import random
import datetime as dt
import copy
import torch.nn as nn

from google.colab import drive
#drive.mount("/content/MyDrive/")

#split

In [ ]:
keep_categories = ["Bottle", "Bottle cap", "Can", "Cigarette", "Cup",
                   "Lid", "Plastic bag & wrapper", "Pop tab", "Straw"]

def create_map(original, keep_supercategories):
  class_map = {}
  for cat in original:
    if cat["supercategory"] in keep_supercategories:
      class_map[cat["name"]] = cat["supercategory"]
    else:
      class_map[cat["name"]] = "Other"
  return class_map

def replace_dataset_classes(dataset, class_map):
      """ Replaces classes of dataset based on a dictionary"""
      class_new_names = list(set(class_map.values()))
      class_new_names.sort()
      class_originals = copy.deepcopy(dataset['categories'])
      dataset['categories'] = []
      class_ids_map = {}  # map from old id to new id

      # Assign background id 0
      has_background = False
      if 'Background' in class_new_names:
          if class_new_names.index('Background') != 0:
              class_new_names.remove('Background')
              class_new_names.insert(0, 'Background')
          has_background = True

      # Replace categories
      for id_new, class_new_name in enumerate(class_new_names):
          # Make sure id:0 is reserved for background
          id_rectified = id_new
          if not has_background:
              id_rectified += 1

          category = {
              'supercategory': '',
              'id': id_rectified,  # Background has id=0
              'name': class_new_name,
          }
          dataset['categories'].append(category)
          # Map class names
          for class_original in class_originals:
              if class_map[class_original['name']] == class_new_name:
                  class_ids_map[class_original['id']] = id_rectified

      # Update annotations category id tag
      for ann in dataset['annotations']:
          ann['category_id'] = class_ids_map[ann['category_id']]


In [ ]:
with open("/content/TACO/data/annotations.json", "r") as f:
    dataset = json.loads(f.read())

class_map = create_map(dataset["categories"], keep_categories)
replace_dataset_classes(dataset, class_map)
dataset["categories"]

{'Aluminium foil': 'Other', 'Battery': 'Other', 'Aluminium blister pack': 'Other', 'Carded blister pack': 'Other', 'Other plastic bottle': 'Bottle', 'Clear plastic bottle': 'Bottle', 'Glass bottle': 'Bottle', 'Plastic bottle cap': 'Bottle cap', 'Metal bottle cap': 'Bottle cap', 'Broken glass': 'Other', 'Food Can': 'Can', 'Aerosol': 'Can', 'Drink can': 'Can', 'Toilet tube': 'Other', 'Other carton': 'Other', 'Egg carton': 'Other', 'Drink carton': 'Other', 'Corrugated carton': 'Other', 'Meal carton': 'Other', 'Pizza box': 'Other', 'Paper cup': 'Cup', 'Disposable plastic cup': 'Cup', 'Foam cup': 'Cup', 'Glass cup': 'Cup', 'Other plastic cup': 'Cup', 'Food waste': 'Other', 'Glass jar': 'Other', 'Plastic lid': 'Lid', 'Metal lid': 'Lid', 'Other plastic': 'Other', 'Magazine paper': 'Other', 'Tissues': 'Other', 'Wrapping paper': 'Other', 'Normal paper': 'Other', 'Paper bag': 'Other', 'Plastified paper bag': 'Other', 'Plastic film': 'Plastic bag & wrapper', 'Six pack rings': 'Plastic bag & wrapp

[{'supercategory': '', 'id': 1, 'name': 'Bottle'},
 {'supercategory': '', 'id': 2, 'name': 'Bottle cap'},
 {'supercategory': '', 'id': 3, 'name': 'Can'},
 {'supercategory': '', 'id': 4, 'name': 'Cigarette'},
 {'supercategory': '', 'id': 5, 'name': 'Cup'},
 {'supercategory': '', 'id': 6, 'name': 'Lid'},
 {'supercategory': '', 'id': 7, 'name': 'Other'},
 {'supercategory': '', 'id': 8, 'name': 'Plastic bag & wrapper'},
 {'supercategory': '', 'id': 9, 'name': 'Pop tab'},
 {'supercategory': '', 'id': 10, 'name': 'Straw'}]

In [ ]:
import os.path
import json
import argparse
import numpy as np
import random
import datetime as dt
import copy
from sklearn.model_selection import train_test_split

"""
parser = argparse.ArgumentParser(description='User args')
parser.add_argument('--dataset_dir', required=True, help='Path to dataset annotations')
parser.add_argument('--test_percentage', type=int, default=10, required=False, help='Percentage of images used for the testing set')
parser.add_argument('--val_percentage', type=int, default=10, required=False, help='Percentage of images used for the validation set')
parser.add_argument('--nr_trials', type=int, default=10, required=False, help='Number of splits')

args = parser.parse_args()
"""
args = {
    "nr_trials":1,
    "test_percentage":0.1,
    "val_percentage":0.1,
    "dataset_dir":'/content/TACO/data'
}

ann_input_path = args["dataset_dir"] + '/annotations_unofficial.json'

# Load annotations
with open(ann_input_path, 'r') as f:
    dataset = json.loads(f.read())

keep_categories = ["Bottle", "Bottle cap", "Can", "Cigarette", "Cup",
                   "Lid", "Plastic bag & wrapper", "Pop tab", "Straw"]
if keep_categories is not None:
  class_map = create_map(dataset["categories"], keep_categories)
  replace_dataset_classes(dataset, class_map)

anns = dataset['annotations']
scene_anns = dataset['scene_annotations']
imgs = dataset['images']
nr_images = len(imgs)

for i in range(args["nr_trials"]):
    random.shuffle(imgs)

    # Add new datasets
    train_set = {
        'info': None,
        'images': [],
        'annotations': [],
        'scene_annotations': [],
        'licenses': [],
        'categories': [],
        'scene_categories': [],
    }
    train_set['info'] =  dataset['info']
    train_set['categories'] = dataset['categories']
    train_set['scene_categories'] = dataset['scene_categories']

    val_set = copy.deepcopy(train_set)
    test_set = copy.deepcopy(train_set)

    train_set['images'], partial = train_test_split(dataset['images'],
                                                    random_state=42,
                                                               test_size=args["test_percentage"]+args["val_percentage"])
    val_set['images'], test_set["images"] = train_test_split(partial,
                                                             random_state=42,
                                                             test_size=args["test_percentage"]/(args["test_percentage"]+args["val_percentage"]))

    # Aux Image Ids to split annotations
    test_img_ids, val_img_ids, train_img_ids = [],[],[]
    for img in test_set['images']:
        test_img_ids.append(img['id'])

    for img in val_set['images']:
        val_img_ids.append(img['id'])

    for img in train_set['images']:
        train_img_ids.append(img['id'])

    # Split instance annotations
    for ann in anns:
        if ann['image_id'] in test_img_ids:
            test_set['annotations'].append(ann)
        elif ann['image_id'] in val_img_ids:
            val_set['annotations'].append(ann)
        elif ann['image_id'] in train_img_ids:
            train_set['annotations'].append(ann)

    # Split scene tags
    for ann in scene_anns:
        if ann['image_id'] in test_img_ids:
            test_set['scene_annotations'].append(ann)
        elif ann['image_id'] in val_img_ids:
            val_set['scene_annotations'].append(ann)
        elif ann['image_id'] in train_img_ids:
            train_set['scene_annotations'].append(ann)

    # Write dataset splits
    ann_train_out_path = args["dataset_dir"] + '/' + 'annotations_' + str(i) +'_train.json'
    ann_val_out_path   = args["dataset_dir"] + '/' + 'annotations_' + str(i) + '_val.json'
    ann_test_out_path  = args["dataset_dir"] + '/' + 'annotations_' + str(i) + '_test.json'

    with open(ann_train_out_path, 'w+') as f:
        f.write(json.dumps(train_set))

    with open(ann_val_out_path, 'w+') as f:
        f.write(json.dumps(val_set))

    with open(ann_test_out_path, 'w+') as f:
        f.write(json.dumps(test_set))


#detr

In [2]:
%cd TACO-expl
import HDDETR.models


/content/TACO-expl


In [3]:
!wget https://github.com/HDETR/H-Deformable-DETR/releases/download/v0.1/r50_hybrid_branch_lambda1_group6_t1500_dp0_mqs_lft_deformable_detr_plus_iterative_bbox_refinement_plus_plus_two_stage_36eps.pth
!mv r50_hybrid_branch_lambda1_group6_t1500_dp0_mqs_lft_deformable_detr_plus_iterative_bbox_refinement_plus_plus_two_stage_36eps.pth r50.pth

--2024-01-14 20:16:32--  https://github.com/HDETR/H-Deformable-DETR/releases/download/v0.1/r50_hybrid_branch_lambda1_group6_t1500_dp0_mqs_lft_deformable_detr_plus_iterative_bbox_refinement_plus_plus_two_stage_36eps.pth
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/517883062/ce62ee7a-43ec-4230-8bf1-348a1530d246?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAVCODYLSA53PQK4ZA%2F20240114%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240114T201633Z&X-Amz-Expires=300&X-Amz-Signature=5840f83ca0e4d81b9da992955462b32988c19c4e8ac19e49686f26d299ccb21a&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=517883062&response-content-disposition=attachment%3B%20filename%3Dr50_hybrid_branch_lambda1_group6_t1500_dp0_mqs_lft_deformable_detr_plus_iterative_bbox_refinement_plus_plus_two_stage

In [4]:
import torch
model = torch.load("r50.pth")

In [5]:
type(model['model'])

collections.OrderedDict

In [6]:
class AttrDict(dict):
    def __init__(self, *args, **kwargs):
        super(AttrDict, self).__init__(*args, **kwargs)
        self.__dict__ = self

args = AttrDict()
args.output_dir = './out/'
args.with_box_refine = True
args.two_stage = True
args.dim_feedforward = 2048
args.num_queries_one2one = 300
args.num_queries_one2many = 1500
args.k_one2many = 6
args.lambda_one2many = 1.0
args.mixed_selection = True
args.look_forward_twice = True
args.dataset_file = "coco"
args.device = 'cuda'
args.hidden_dim = 256
args.position_embedding = 'sine'
args.position_embedding_scale = np.pi *2
#args.lr_backbone =2e-5
args.lr_backbone = 0
args.masks = False
args.num_feature_levels = 4
args.backbone = "resnet50"
args.dilation = False
args.nheads = 8
args.enc_layers = 6
args.dec_layers = 6
args.dim_feedforwards = 2048
args.dropout = 0
args.dec_n_points = 4
args.enc_n_points = 4
args.use_checkpoint = True
args.aux_loss = True
args.cls_loss_coef=2
args.giou_loss_coef=2
args.focal_alpha=0.25
args.topk=100
args.bbox_loss_coef=5
args.set_cost_class=2
args.set_cost_bbox=5
args.set_cost_giou=2

In [7]:
model,crit, postproc = HDDETR.models.build(args)

/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


topk for eval: 100


In [8]:
model.load_state_dict(torch.load("r50.pth")["model"])

<All keys matched successfully>

In [9]:
from HDDETR.util.misc import NestedTensor
from PIL import Image
import torch
from torchvision import transforms

dev = torch.device("cuda")
model.to(dev)
to_t = transforms.ToTensor()
img = Image.open("treno.jpg")
a = to_t(img).reshape((1,3,640,480))
a = a.to(dev)
mask = torch.zeros((1,640,480), dtype=torch.bool, device=dev)
mask = mask.to(dev)
nt = NestedTensor(a, mask)
nt = nt.to(dev)

In [10]:
out = model(nt)

tensor([   0, 4800, 6000, 6300], device='cuda:0')
tensor([[80, 60],
        [40, 30],
        [20, 15],
        [10,  8]], device='cuda:0')
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]], device='cuda:0')
tensor([[[ 0.1514,  1.0120,  0.0590,  ...,  0.3137,  1.3566,  0.1682],
         [ 0.1514,  1.0120,  0.0590,  ...,  0.3137,  1.3566,  0.1682],
         [ 0.1514,  1.0120,  0.0590,  ...,  0.3137,  1.3566,  0.1682],
         ...,
         [ 0.6646,  0.4375, -0.5388,  ..., -0.2039, -0.2458,  2.5909],
         [ 0.6646,  0.4375, -0.5388,  ..., -0.2039, -0.2457,  2.5909],
         [ 0.6646,  0.4375, -0.5388,  ..., -0.2039, -0.2456,  2.5909]]],
       device='cuda:0', grad_fn=<CatBackward0>)
tensor([   0, 4800, 6000, 6300], device='cuda:0')


/usr/local/lib/python3.10/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


tensor([   0, 4800, 6000, 6300], device='cuda:0')
tensor([   0, 4800, 6000, 6300], device='cuda:0')
tensor([   0, 4800, 6000, 6300], device='cuda:0')
tensor([   0, 4800, 6000, 6300], device='cuda:0')
tensor([   0, 4800, 6000, 6300], device='cuda:0')


In [ ]:
for k in out.keys():
  print(k)
  print(type(out[k]))

  if type(out[k]) == torch.Tensor:
    print(out[k].shape)
  else:
    print(out[k])

decoder_out
<class 'torch.Tensor'>
torch.Size([6, 1, 1800, 256])
pred_logits
<class 'torch.Tensor'>
torch.Size([1, 300, 91])
pred_boxes
<class 'torch.Tensor'>
torch.Size([1, 300, 4])
pred_logits_one2many
<class 'torch.Tensor'>
torch.Size([1, 1500, 91])
pred_boxes_one2many
<class 'torch.Tensor'>
torch.Size([1, 1500, 4])
backbone_out
<class 'torch.Tensor'>
torch.Size([1, 256, 160, 120])
intermediate_enc_out
<class 'torch.Tensor'>
torch.Size([1, 6380, 1024])
aux_outputs
<class 'list'>
[{'pred_logits': tensor([[[-9.1464, -5.4714, -6.6855,  ..., -7.2224, -5.6382, -5.7590],
         [-9.4401, -5.2760, -6.4668,  ..., -6.9920, -5.5224, -5.7362],
         [-9.3116, -5.3722, -6.6665,  ..., -7.0782, -6.0493, -6.0677],
         ...,
         [-9.5011, -5.5192, -7.4980,  ..., -8.1119, -7.0149, -6.5823],
         [-9.2461, -5.0731, -6.0116,  ..., -5.9315, -5.1204, -5.7667],
         [-9.0631, -6.3629, -7.4295,  ..., -8.3089, -6.6256, -6.0667]]],
       device='cuda:0', grad_fn=<UnbindBackward0>), 'p

In [ ]:
from HDDETR.models.deformable_transformer import DeformableTransformerEncoderLayer
from torchvision.ops import ROIAlign
from HDDETR.util.misc import interpolate
class MaskFrozenDETR(nn.Module):
  def __init__(self, detr, device):
    super.__init__()
    self.device = device
    self.detr = detr
    for param in detr.parameters():
      param.requires_grad = False
    # vedi deformable encoder block
    self.feature_enc_1 = DeformableTransformerEncoderLayer(d_model=256,dropout=0, activation='gelu')
    self.feature_enc_2 = DeformableTransformerEncoderLayer(d_model=256,dropout=0, activation='gelu')
    self.box_enc_1 = DeformableTransformerEncoderLayer(d_model=128,dropout=0, activation='gelu')
    self.box_enc_2 = DeformableTransformerEncoderLayer(d_model=128,dropout=0, activation='gelu')
    self.channel_mapper = nn.Linear(256, 128)
    self.query_channel_mapper = nn.Linear(256, 128)
    self.roialign = ROIAlign(output_size=(32,32),spatial_scale=0.25 )
    self.class_adapter1 = nn.linear(91, 10)
    self.class_adapter2 = nn.linear(48, 10)
    self.topk = 100
  def forward(self, input, sizes):
    bs, _, h, w = input.tensors.shape
    detr_out = self.detr(input)

    ref_points = self.detr.transformer.encoder.get_reference_points(detr_out["intermediate_enc_out"]["spatial_shapes"],
                                                                    detr_out["intermediate_enc_out"]["valid_ratios"],
                                                                    self.device)
    enc_maps = self.feature_enc_1(**detr_out["intermediate_enc_out"], reference_points=ref_points)
    detr_out["intermediate_enc_out"]["src"] = enc_maps
    enc_maps = self.feature_enc_2(**detr_out["intermediate_enc_out"], reference_points=ref_points).permute(0, 2, 1)
    fe = interpolate(enc_maps, detr_out["backbone_out"].shape, "bilnear")
    f = detr_out["backbone_out"].view((bs, 256, -1 )) + fe
    mapped_f = self.channel_mapper(f)


    logits = detr_out['pred_logits']
    logits = self.class_adapter1(logits)
    logits = self.class_adapter2(logits)
    ci = logits.sigmoid()
    topk_values, topk_indexes = torch.topk(
            ci.view(logits.shape[0], -1), self.topk, dim=1
    )
    topk_boxes = topk_indexes // logits.shape[2]
    boxes = box_ops.box_cxcywh_to_xyxy(detr_out["pred_boxes"])
    boxes = torch.gather(boxes, 1, topk_boxes.unsqueeze(-1).repeat(1, 1, 4))
    img_h, img_w = sizes.unbind(1)
    scale_fct = torch.stack([img_w, img_h, img_w, img_h], dim=1)
    boxes = boxes * scale_fct[:, None, :]
    object_queries = detr_out["decoder_out"][-1, :, :self.detr.num_queries_one2one, :]
    object_queries = torch.gather(object_queries, 1, topk_boxes.unsqueeze(-1).repeat(1,1,object_queries.shape[-1]))

    batchindexes = torch.arange(bs).reshape(bs,1,1).repeat(1,self.topk,1)
    boxes = torch.cat([batchindexes, boxes], -1).reshape(bs*self.topk, 5)
    Ri = ROIAlign(mapped_f.reshape((bs, 128, h//4, w//4 )), boxes)
    maskRi = ROIAlign(detr_out["intermediate_enc_out"]["padding_mask"].reshape((bs,h//4, w//4 )), object_queries)
    Ri = Ri.permute(0, 2, 3, 1).reshape(bs*self.topk,32*32, 128) # ?
    valid_ratios_box = torch.stack([self.detr.transformer.get_valid_ratio(m) for m in maskRi], 1)
    ref_point_box = self.detr.transformer.encoder.get_reference_points(torch.tensor([[32,32]]),
                                                                    valid_ratios_box,
                                                                    self.device)
    Ri = self.box_enc_1(Ri, padding_mask=maskRi,
                        level_start_index=torch.tensor([0]),
                        pos=None,
                        reference_points=ref_point_box,
                        spatial_shapes=torch.tensor([[32,32]]))
    Ri = self.box_enc_2(Ri, padding_mask=maskRi,
                        level_start_index=torch.tensor([0]),
                        pos=None,
                        reference_points=ref_point_box,
                        spatial_shapes=torch.tensor([[32,32]])))
    object_queries = self.query_channel_mapper(objecy_queries).reshape(bs*self.topk, 128)
    segmasks = torch.bmm(object_queries, torch.transpose(Ri, 1,2)).sigmoid().reshape(bs, 100, 32, 32)
    segmasks = interpolate()
    # prendere la maschera con i confidence score più alti ?
    # vedere build_model + engine
    # TODO: capire come selezionare le maschere




SyntaxError: ignored